version: '3'
services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./laravel:/var/www/html
    networks:
      - app-network

  webserver:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./laravel:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=hostit
      - MYSQL_PASSWORD=laravel
      - MYSQL_ROOT_PASSWORD=laravel
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        - PMA_HOST=db
        - PMA_USER=root
        - PMA_PASSWORD=laravel
        - PMA_PORT=3306
        - PMA_ARBITRARY=1
      ports:
          - 8093:80
      networks:
          - app-network
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
